spring:
  application:
    name: semicolon
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_service}?sslmode=${DB_SSLMODE:disable}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 100

  jackson:
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false

  batch:
    initialize-schema: always
    job:
      enabled: false  # 애플리케이션 시작 시 자동 실행 방지

  elasticsearch:
    Uris: http://elasticsearch:9200  # ES 서버 주소
    socket-timeout: 30s
    connection-timeout: 5s

batch:
  settlement:
    chunk-size: 100
    fee-rate: 0.05
    skip-limit: 10
    retry-limit: 3
    page-size: 100
    scheduler:
        enabled: true
        cron: "0 0 0 * * *"  # 매일 자정 실행

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
    operations-sorter: method

server:
  forward-headers-strategy: framework

redis:
  product:
    view:
      prefix: "product:view:"
      dirty-key: "product:view:dirty"